sudo: false
language: rust
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - binutils-dev
rust:
- stable
- nightly
- beta
matrix:
  allow_failures:
  - rust: nightly
  fast_finish: true
before_script:
- |
  pip install 'travis-cargo<0.2' --user &&
  export PATH=$HOME/.local/bin:$PATH
script:
- |
  travis-cargo build &&
  travis-cargo test &&
  travis-cargo bench &&
  travis-cargo --only stable doc
after_success:
- travis-cargo --only stable doc-upload
env:
  global:
  - TRAVIS_CARGO_NIGHTLY_FEATURE=nightly
  - secure: TmrNAlM/cgBoygV4hbCbNaCTzkDNSqvGGHjESsq7U4lPriKPUmeUgmReUNq9koblBcQONyRzMvTyNo4nrbV2w/W1tSy5VLT/ZxW7jP07CWoWRbbIXR0RfdQMzDxNTHyXd20XXMSWd7yHinzeacXMYYJlIyH3S7s5o2DzB+QJw35bl7pj6qg8swUCRdLXHW6VlOg7AYzosbgyjH67KHS4jJ/CTuEYgRE6XflCiwche07N4aWOdEarzKkNmPIeKjNv3ASJ1dWQ+CuQ7nsLvqWCqNl5arQVs4LvEUpZOCmfzQ1VoFMkwa+tzUiUXhA8maA2CIkymNUMv5QH4QdLjdUT8yH718Nk3uyQTQV0wmjJPVZ5L/rUKERhrN6I8x0U4xVsoPmm6xgzqCjG62zHXcUj/wTd1Q35SO2wJpEmaJHGdOHahuHsBsv2XK5t4LNbJnB64pLwMxkKael6ya14y4iNpE0yd7NGw7VVwK1v/nvnUVDIywOY/GNvRc+Mh/x5RIBNRyZFGKb+shLYsULMXpdpbPb/05pnu3X8tJVPHaYYm7OH4kG/+BleyDhxu+OK06RksFyI1hYQexrF19x+C3wKNSSL5pD/I/nXJj9d+t8a8Cn3uwUSczjT9+qa9tvXPVFd8NPArt8WtBu5BEp0SjwhcskU+6v/Ka3izmfpDFYh4Mo=
